# Generated by Django 5.0.6 on 2024-07-19 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CatBreed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_type', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_breed', to='shop.catalog')),
            ],
        ),
        migrations.CreateModel(
            name='CatCoat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coat_type', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_coat', to='shop.catalog')),
            ],
        ),
        migrations.CreateModel(
            name='DogBreed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_type', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dog_breed', to='shop.catalog')),
            ],
        ),
        migrations.CreateModel(
            name='DogCoat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coat_type', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dog_coat', to='shop.catalog')),
            ],
        ),
        migrations.CreateModel(
            name='DogSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dog_size', to='shop.catalog')),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='dog_images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.catalog')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.dogbreed')),
                ('coat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.dogcoat')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.dogsize')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.gender')),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='cat_images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.catalog')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.catbreed')),
                ('coat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.catcoat')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.gender')),
            ],
        ),
        migrations.CreateModel(
            name='RabbitColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_type', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rabbit_color', to='shop.catalog')),
            ],
        ),
        migrations.CreateModel(
            name='RabbitFur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fur_type', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rabbit_fur', to='shop.catalog')),
            ],
        ),
        migrations.CreateModel(
            name='Rabbit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rabbit_name', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('images', models.ImageField(upload_to='rabbits_images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.catalog')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.gender')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.rabbitcolor')),
                ('fur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.rabbitfur')),
            ],
        ),
    ]
