# Generated by Django 5.0.6 on 2024-07-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='avaible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='avaible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rabbit',
            name='avaible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dog',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rabbit',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
