# Generated by Django 5.0.6 on 2024-07-29 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_cat_name_cat_name_rename_dog_name_dog_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='category',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='coat',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='size',
        ),
        migrations.RemoveField(
            model_name='rabbit',
            name='category',
        ),
        migrations.RemoveField(
            model_name='rabbit',
            name='color',
        ),
        migrations.RemoveField(
            model_name='rabbit',
            name='fur',
        ),
        migrations.RemoveField(
            model_name='rabbit',
            name='gender',
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('cat', 'Cat'), ('dog', 'Dog'), ('rabbit', 'Rabbit')], max_length=30)),
                ('name', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('images', models.ImageField(upload_to='product_images')),
                ('avaible', models.BooleanField(default=True)),
                ('breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breed_set', to='shop.pets')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.catalog')),
                ('coat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coat_set', to='shop.pets')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color_set', to='shop.pets')),
                ('fur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fur_set', to='shop.pets')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.gender')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size_set', to='shop.pets')),
            ],
        ),
        migrations.DeleteModel(
            name='Cat',
        ),
        migrations.DeleteModel(
            name='Dog',
        ),
        migrations.DeleteModel(
            name='Rabbit',
        ),
    ]
