# Generated by Django 5.0.6 on 2024-07-29 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_dog_breed_remove_dog_category_remove_dog_coat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Coat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Fur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='catcoat',
            name='category',
        ),
        migrations.RemoveField(
            model_name='dogbreed',
            name='category',
        ),
        migrations.RemoveField(
            model_name='dogcoat',
            name='category',
        ),
        migrations.RemoveField(
            model_name='dogsize',
            name='category',
        ),
        migrations.RemoveField(
            model_name='rabbitcolor',
            name='category',
        ),
        migrations.RemoveField(
            model_name='rabbitfur',
            name='category',
        ),
        migrations.AlterField(
            model_name='pets',
            name='breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breed_set', to='shop.breed'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='coat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coat_set', to='shop.coat'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color_set', to='shop.color'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='fur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fur_set', to='shop.fur'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size_set', to='shop.size'),
        ),
        migrations.DeleteModel(
            name='CatBreed',
        ),
        migrations.DeleteModel(
            name='CatCoat',
        ),
        migrations.DeleteModel(
            name='DogBreed',
        ),
        migrations.DeleteModel(
            name='DogCoat',
        ),
        migrations.DeleteModel(
            name='DogSize',
        ),
        migrations.DeleteModel(
            name='RabbitColor',
        ),
        migrations.DeleteModel(
            name='RabbitFur',
        ),
    ]
