# Generated by Django 5.0.6 on 2024-07-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_breed_coat_color_fur_size_remove_catcoat_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
