# Generated by Django 5.1 on 2024-09-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_prodcomment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodcomment',
            name='user',
        ),
        migrations.AddField(
            model_name='prodcomment',
            name='user_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
