# Generated by Django 5.1 on 2024-09-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_prodcomment_user_prodcomment_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodcomment',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
    ]
