# Generated by Django 5.0.6 on 2024-08-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_profile_city_remove_profile_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background_pic',
            field=models.ImageField(blank=True, default='background_pic/profile-picture-background-1uip4ytll6lbmfp5.jpg', null=True, upload_to='background_pic'),
        ),
    ]
