# Generated by Django 5.0.6 on 2024-08-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_profile_background_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='user_avatars/default avatar.webp', null=True, upload_to='user_avatars'),
        ),
    ]
